Update flake & cargo dependencies
Needed so that it builds with Rust 1.80 again, currently it fails for me
with

    error[E0282]: type annotations needed for `Box<_>`
      --> /nix/store/1s1dfkw9b28iy8nbc6mybn2fx6j1cll0-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0/time-0.3.34/src/format_description/parse/mod.rs:83:9
       |
    83 |     let items = format_items
       |         ^^^^^
    ...
    86 |     Ok(items.into())
       |              ---- type must be known at this point
       |
    help: consider giving `items` an explicit type, where the placeholders `_` are specified
       |
    83 |     let items: Box<_> = format_items
       |              ++++++++

        Checking regex-automata v0.4.6
        Checking nb-connect v1.2.0
        Checking indicatif v0.17.8
       Compiling rand v0.8.5
        Checking tempfile v3.10.1
    For more information about this error, try `rustc --explain E0282`.
    error: could not compile `time` (lib) due to 1 previous error
    warning: build failed, waiting for other jobs to finish...