Regenerate `Cargo.lock` via `cargo vendor` for `0.2.9`
Otherwise, the build would fail like this when using `cargo build
--frozen` which is e.g. the case when building Rust code with Nix[1]:

```
error: the lock file /build/source/Cargo.lock needs to be updated but --frozen was passed to prevent this
```

[1] https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md